-- Compartir notas con contactos
-- Ejecuta en Supabase → SQL Editor → Run

create table if not exists public.note_shares (
  id bigint generated by default as identity primary key,
  note_id uuid not null references public.notes (id) on delete cascade,
  shared_with uuid not null references public.profiles (id) on delete cascade,
  shared_by uuid not null references public.profiles (id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now(),
  constraint note_shares_unique unique (note_id, shared_with),
  constraint note_shares_not_self check (shared_with <> shared_by)
);

create index if not exists note_shares_note_id_idx on public.note_shares (note_id);
create index if not exists note_shares_shared_with_idx on public.note_shares (shared_with);

alter table public.note_shares enable row level security;

drop policy if exists "Users can select related note shares" on public.note_shares;
drop policy if exists "Users can insert own note shares" on public.note_shares;
drop policy if exists "Users can delete own note shares" on public.note_shares;

create policy "Users can select related note shares"
  on public.note_shares for select
  using (auth.uid() = shared_by or auth.uid() = shared_with);

create policy "Users can insert own note shares"
  on public.note_shares for insert
  with check (auth.uid() = shared_by);

create policy "Users can delete own note shares"
  on public.note_shares for delete
  using (auth.uid() = shared_by);

-- Helper: ¿esta nota está compartida conmigo?
create or replace function public.note_is_shared_with_me(p_note_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.note_shares s
    where s.note_id = p_note_id
      and s.shared_with = auth.uid()
  );
$$;

grant execute on function public.note_is_shared_with_me(uuid) to authenticated;

-- Actualizar RLS en notas para permitir a los que tengan acceso ver y editar
drop policy if exists "Users can select own notes" on public.notes;
create policy "Users can select own notes"
  on public.notes for select
  using (auth.uid() = user_id or public.note_is_shared_with_me(id));

drop policy if exists "Users can update own notes" on public.notes;
create policy "Users can update own notes"
  on public.notes for update
  using (auth.uid() = user_id or public.note_is_shared_with_me(id))
  with check (auth.uid() = user_id or public.note_is_shared_with_me(id));
