-- Crear tabla de tableros (boards)
CREATE TABLE IF NOT EXISTS boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    color TEXT DEFAULT '#ffffff',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en boards
ALTER TABLE boards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver sus propios tableros"
    ON boards FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Los usuarios pueden crear tableros"
    ON boards FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Los usuarios pueden actualizar sus propios tableros"
    ON boards FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Los usuarios pueden borrar sus propios tableros"
    ON boards FOR DELETE
    USING (auth.uid() = user_id);

-- Añadir board_id y status a la tabla tasks
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS board_id BIGINT REFERENCES boards(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'backlog';

-- Actualizar RLS de tasks (si es necesario) para permitir actualización de board_id y status
-- Dado que la política actual probablemente usa auth.uid() = user_id, los nuevos campos quedan cubiertos automáticamente.
