-- Tabla de Listas (Columnas) Dinámicas
create table if not exists public.board_lists (
  id bigint generated by default as identity primary key,
  board_id bigint not null references public.boards (id) on delete cascade,
  name text not null,
  color text default 'bg-brand-surface',
  order_index integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.board_lists enable row level security;

create policy "Users can select their board lists"
  on public.board_lists for select
  using (
    exists (
      select 1 from public.boards b
      where b.id = board_lists.board_id and b.user_id = auth.uid()
    )
  );

create policy "Users can insert their board lists"
  on public.board_lists for insert
  with check (
    exists (
      select 1 from public.boards b
      where b.id = board_id and b.user_id = auth.uid()
    )
  );

create policy "Users can update their board lists"
  on public.board_lists for update
  using (
    exists (
      select 1 from public.boards b
      where b.id = board_id and b.user_id = auth.uid()
    )
  );

create policy "Users can delete their board lists"
  on public.board_lists for delete
  using (
    exists (
      select 1 from public.boards b
      where b.id = board_id and b.user_id = auth.uid()
    )
  );

-- Add list_id to tasks
alter table public.tasks add column if not exists list_id bigint references public.board_lists (id) on delete cascade;

-- Trigger to auto-create default lists for new boards
create or replace function public.create_default_board_lists()
returns trigger as $$
begin
  insert into public.board_lists (board_id, name, order_index, color)
  values 
    (new.id, 'Por Hacer / Backlog', 0, 'bg-brand-surface'),
    (new.id, 'En Progreso', 1, 'bg-brand-surface'),
    (new.id, 'En Revisión / Pausa', 2, 'bg-brand-surface'),
    (new.id, 'Completado', 3, 'bg-brand-surface');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_board_created on public.boards;
create trigger on_board_created
  after insert on public.boards
  for each row execute function public.create_default_board_lists();

-- Migrate existing boards to have the 4 default lists
do $$
declare
  b record;
begin
  for b in select id from public.boards loop
    if not exists (select 1 from public.board_lists where board_id = b.id) then
      insert into public.board_lists (board_id, name, order_index, color)
      values 
        (b.id, 'Por Hacer / Backlog', 0, 'bg-brand-surface'),
        (b.id, 'En Progreso', 1, 'bg-brand-surface'),
        (b.id, 'En Revisión / Pausa', 2, 'bg-brand-surface'),
        (b.id, 'Completado', 3, 'bg-brand-surface');
    end if;
  end loop;
end;
$$;

-- Migrate existing tasks from text 'status' to the new 'list_id'
do $$
declare
  t record;
  l_id bigint;
begin
  for t in select id, board_id, status from public.tasks where list_id is null loop
    if t.status = 'backlog' then
      select id into l_id from public.board_lists where board_id = t.board_id and order_index = 0 limit 1;
    elsif t.status = 'progress' then
      select id into l_id from public.board_lists where board_id = t.board_id and order_index = 1 limit 1;
    elsif t.status = 'review' then
      select id into l_id from public.board_lists where board_id = t.board_id and order_index = 2 limit 1;
    elsif t.status = 'completed' then
      select id into l_id from public.board_lists where board_id = t.board_id and order_index = 3 limit 1;
    else
      select id into l_id from public.board_lists where board_id = t.board_id and order_index = 0 limit 1;
    end if;
    
    update public.tasks set list_id = l_id where id = t.id;
  end loop;
end;
$$;
