-- Migration 020: Finance Module
-- Creates tables for finance boards, categories, subcategories, accounts, and transactions.

-- 1. Finance Boards
CREATE TABLE public.finance_boards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_boards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own finance boards" 
ON public.finance_boards FOR ALL 
USING (auth.uid() = user_id);


-- 2. Finance Accounts / Payment Methods
CREATE TABLE public.finance_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT REFERENCES public.finance_boards(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- e.g., 'cash', 'bank', 'credit_card'
    initial_balance NUMERIC(15, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage accounts of their boards" 
ON public.finance_accounts FOR ALL 
USING (
    board_id IN (SELECT id FROM public.finance_boards WHERE user_id = auth.uid())
);


-- 3. Finance Categories (Parent)
CREATE TABLE public.finance_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT REFERENCES public.finance_boards(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'income' or 'expense'
    color TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage categories of their boards" 
ON public.finance_categories FOR ALL 
USING (
    board_id IN (SELECT id FROM public.finance_boards WHERE user_id = auth.uid())
);


-- 4. Finance Subcategories (Child)
CREATE TABLE public.finance_subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_subcategories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage subcategories of their boards" 
ON public.finance_subcategories FOR ALL 
USING (
    category_id IN (
        SELECT fc.id FROM public.finance_categories fc
        JOIN public.finance_boards fb ON fc.board_id = fb.id
        WHERE fb.user_id = auth.uid()
    )
);


-- 5. Finance Transactions
CREATE TABLE public.finance_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id BIGINT REFERENCES public.finance_boards(id) ON DELETE CASCADE,
    account_id BIGINT REFERENCES public.finance_accounts(id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES public.finance_categories(id) ON DELETE SET NULL,
    subcategory_id BIGINT REFERENCES public.finance_subcategories(id) ON DELETE SET NULL,
    amount NUMERIC(15, 2) NOT NULL,
    type TEXT NOT NULL, -- 'income' or 'expense'
    description TEXT,
    date DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.finance_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage transactions of their boards" 
ON public.finance_transactions FOR ALL 
USING (
    board_id IN (SELECT id FROM public.finance_boards WHERE user_id = auth.uid())
);
